### ISSUE TITLE
Sorting Algorithms

### ISSUE THREAD

**Issue by deepanshu-rawat6** [Med16-11/365daysOfCode#9]
@Med16-11 Ma'am can I add some sorting algorithms codes in Java?
List:
1. Quick Sort
2. Merge Sort
3. Bubble Sort
4. Selection Sort
5. Insertion Sort

**Comment by Med16-11** [comment]
Sure @deepanshu-rawat6 ! Just add a folder with the name "Java" inside the sorting algo folder and add all your codes inside that(Java) folder.

**Comment by Ashwin-5100** [comment]
Hello @Med16-11  ,
Can you please assign me this issue ??

**Comment by Med16-11** [comment]
Hey this task is already completed, you can raise another issue !
